// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: first.proto

package first_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test1Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meassage string `protobuf:"bytes,1,opt,name=meassage,proto3" json:"meassage,omitempty"`
}

func (x *Test1Req) Reset() {
	*x = Test1Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test1Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1Req) ProtoMessage() {}

func (x *Test1Req) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1Req.ProtoReflect.Descriptor instead.
func (*Test1Req) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{0}
}

func (x *Test1Req) GetMeassage() string {
	if x != nil {
		return x.Meassage
	}
	return ""
}

type Test1Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meassage string `protobuf:"bytes,1,opt,name=meassage,proto3" json:"meassage,omitempty"`
}

func (x *Test1Res) Reset() {
	*x = Test1Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test1Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test1Res) ProtoMessage() {}

func (x *Test1Res) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test1Res.ProtoReflect.Descriptor instead.
func (*Test1Res) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{1}
}

func (x *Test1Res) GetMeassage() string {
	if x != nil {
		return x.Meassage
	}
	return ""
}

var File_first_proto protoreflect.FileDescriptor

var file_first_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x54,
	0x65, 0x73, 0x74, 0x31, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x31, 0x52, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x47, 0x0a, 0x0c, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x54,
	0x65, 0x73, 0x74, 0x31, 0x12, 0x16, 0x2e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x31, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x31, 0x52, 0x65, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_first_proto_rawDescOnce sync.Once
	file_first_proto_rawDescData = file_first_proto_rawDesc
)

func file_first_proto_rawDescGZIP() []byte {
	file_first_proto_rawDescOnce.Do(func() {
		file_first_proto_rawDescData = protoimpl.X.CompressGZIP(file_first_proto_rawDescData)
	})
	return file_first_proto_rawDescData
}

var file_first_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_first_proto_goTypes = []interface{}{
	(*Test1Req)(nil), // 0: firstservice.Test1Req
	(*Test1Res)(nil), // 1: firstservice.Test1Res
}
var file_first_proto_depIdxs = []int32{
	0, // 0: firstservice.FirstService.Test1:input_type -> firstservice.Test1Req
	1, // 1: firstservice.FirstService.Test1:output_type -> firstservice.Test1Res
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_first_proto_init() }
func file_first_proto_init() {
	if File_first_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_first_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test1Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test1Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_first_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_first_proto_goTypes,
		DependencyIndexes: file_first_proto_depIdxs,
		MessageInfos:      file_first_proto_msgTypes,
	}.Build()
	File_first_proto = out.File
	file_first_proto_rawDesc = nil
	file_first_proto_goTypes = nil
	file_first_proto_depIdxs = nil
}
