// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: first.proto

package first_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirstServiceClient is the client API for FirstService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstServiceClient interface {
	Test1(ctx context.Context, in *Test1Req, opts ...grpc.CallOption) (*Test1Res, error)
}

type firstServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstServiceClient(cc grpc.ClientConnInterface) FirstServiceClient {
	return &firstServiceClient{cc}
}

func (c *firstServiceClient) Test1(ctx context.Context, in *Test1Req, opts ...grpc.CallOption) (*Test1Res, error) {
	out := new(Test1Res)
	err := c.cc.Invoke(ctx, "/firstservice.FirstService/Test1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstServiceServer is the server API for FirstService service.
// All implementations must embed UnimplementedFirstServiceServer
// for forward compatibility
type FirstServiceServer interface {
	Test1(context.Context, *Test1Req) (*Test1Res, error)
	mustEmbedUnimplementedFirstServiceServer()
}

// UnimplementedFirstServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFirstServiceServer struct {
}

func (UnimplementedFirstServiceServer) Test1(context.Context, *Test1Req) (*Test1Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test1 not implemented")
}
func (UnimplementedFirstServiceServer) mustEmbedUnimplementedFirstServiceServer() {}

// UnsafeFirstServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstServiceServer will
// result in compilation errors.
type UnsafeFirstServiceServer interface {
	mustEmbedUnimplementedFirstServiceServer()
}

func RegisterFirstServiceServer(s grpc.ServiceRegistrar, srv FirstServiceServer) {
	s.RegisterService(&FirstService_ServiceDesc, srv)
}

func _FirstService_Test1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test1Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServiceServer).Test1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firstservice.FirstService/Test1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServiceServer).Test1(ctx, req.(*Test1Req))
	}
	return interceptor(ctx, in, info, handler)
}

// FirstService_ServiceDesc is the grpc.ServiceDesc for FirstService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirstService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firstservice.FirstService",
	HandlerType: (*FirstServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test1",
			Handler:    _FirstService_Test1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "first.proto",
}
