// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: clients.proto

package tender_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	CreateTender(ctx context.Context, in *CreateTenderReq, opts ...grpc.CallOption) (*ResponseMessage, error)
	GetMyTenders(ctx context.Context, in *GetMyTendersReq, opts ...grpc.CallOption) (*TendersList, error)
	GetAllTenders(ctx context.Context, in *GetAllTendersReq, opts ...grpc.CallOption) (*TendersList, error)
	UpdateTenderStatus(ctx context.Context, in *UpdateTenderStatusReq, opts ...grpc.CallOption) (*ResponseMessage, error)
	DeleteTender(ctx context.Context, in *DeleteTenderReq, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CreateTender(ctx context.Context, in *CreateTenderReq, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/tender.ClientService/CreateTender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetMyTenders(ctx context.Context, in *GetMyTendersReq, opts ...grpc.CallOption) (*TendersList, error) {
	out := new(TendersList)
	err := c.cc.Invoke(ctx, "/tender.ClientService/GetMyTenders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetAllTenders(ctx context.Context, in *GetAllTendersReq, opts ...grpc.CallOption) (*TendersList, error) {
	out := new(TendersList)
	err := c.cc.Invoke(ctx, "/tender.ClientService/GetAllTenders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateTenderStatus(ctx context.Context, in *UpdateTenderStatusReq, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/tender.ClientService/UpdateTenderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) DeleteTender(ctx context.Context, in *DeleteTenderReq, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/tender.ClientService/DeleteTender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility
type ClientServiceServer interface {
	CreateTender(context.Context, *CreateTenderReq) (*ResponseMessage, error)
	GetMyTenders(context.Context, *GetMyTendersReq) (*TendersList, error)
	GetAllTenders(context.Context, *GetAllTendersReq) (*TendersList, error)
	UpdateTenderStatus(context.Context, *UpdateTenderStatusReq) (*ResponseMessage, error)
	DeleteTender(context.Context, *DeleteTenderReq) (*ResponseMessage, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (UnimplementedClientServiceServer) CreateTender(context.Context, *CreateTenderReq) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTender not implemented")
}
func (UnimplementedClientServiceServer) GetMyTenders(context.Context, *GetMyTendersReq) (*TendersList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyTenders not implemented")
}
func (UnimplementedClientServiceServer) GetAllTenders(context.Context, *GetAllTendersReq) (*TendersList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTenders not implemented")
}
func (UnimplementedClientServiceServer) UpdateTenderStatus(context.Context, *UpdateTenderStatusReq) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenderStatus not implemented")
}
func (UnimplementedClientServiceServer) DeleteTender(context.Context, *DeleteTenderReq) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTender not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_CreateTender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateTender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ClientService/CreateTender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateTender(ctx, req.(*CreateTenderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetMyTenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyTendersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetMyTenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ClientService/GetMyTenders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetMyTenders(ctx, req.(*GetMyTendersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetAllTenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTendersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetAllTenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ClientService/GetAllTenders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetAllTenders(ctx, req.(*GetAllTendersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateTenderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenderStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateTenderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ClientService/UpdateTenderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateTenderStatus(ctx, req.(*UpdateTenderStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_DeleteTender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).DeleteTender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tender.ClientService/DeleteTender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).DeleteTender(ctx, req.(*DeleteTenderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tender.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTender",
			Handler:    _ClientService_CreateTender_Handler,
		},
		{
			MethodName: "GetMyTenders",
			Handler:    _ClientService_GetMyTenders_Handler,
		},
		{
			MethodName: "GetAllTenders",
			Handler:    _ClientService_GetAllTenders_Handler,
		},
		{
			MethodName: "UpdateTenderStatus",
			Handler:    _ClientService_UpdateTenderStatus_Handler,
		},
		{
			MethodName: "DeleteTender",
			Handler:    _ClientService_DeleteTender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
