// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/contractors.proto

package tender_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractorService_SubmitBid_FullMethodName        = "/tender.ContractorService/SubmitBid"
	ContractorService_GetBidsForTender_FullMethodName = "/tender.ContractorService/GetBidsForTender"
	ContractorService_GetMyBids_FullMethodName        = "/tender.ContractorService/GetMyBids"
)

// ContractorServiceClient is the client API for ContractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractorServiceClient interface {
	SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error)
	GetBidsForTender(ctx context.Context, in *GetBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error)
	GetMyBids(ctx context.Context, in *GetMyBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error)
}

type contractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractorServiceClient(cc grpc.ClientConnInterface) ContractorServiceClient {
	return &contractorServiceClient{cc}
}

func (c *contractorServiceClient) SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, ContractorService_SubmitBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractorServiceClient) GetBidsForTender(ctx context.Context, in *GetBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidsListResponse)
	err := c.cc.Invoke(ctx, ContractorService_GetBidsForTender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractorServiceClient) GetMyBids(ctx context.Context, in *GetMyBidsRequest, opts ...grpc.CallOption) (*BidsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidsListResponse)
	err := c.cc.Invoke(ctx, ContractorService_GetMyBids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractorServiceServer is the server API for ContractorService service.
// All implementations must embed UnimplementedContractorServiceServer
// for forward compatibility.
type ContractorServiceServer interface {
	SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error)
	GetBidsForTender(context.Context, *GetBidsRequest) (*BidsListResponse, error)
	GetMyBids(context.Context, *GetMyBidsRequest) (*BidsListResponse, error)
	mustEmbedUnimplementedContractorServiceServer()
}

// UnimplementedContractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractorServiceServer struct{}

func (UnimplementedContractorServiceServer) SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBid not implemented")
}
func (UnimplementedContractorServiceServer) GetBidsForTender(context.Context, *GetBidsRequest) (*BidsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBidsForTender not implemented")
}
func (UnimplementedContractorServiceServer) GetMyBids(context.Context, *GetMyBidsRequest) (*BidsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyBids not implemented")
}
func (UnimplementedContractorServiceServer) mustEmbedUnimplementedContractorServiceServer() {}
func (UnimplementedContractorServiceServer) testEmbeddedByValue()                           {}

// UnsafeContractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractorServiceServer will
// result in compilation errors.
type UnsafeContractorServiceServer interface {
	mustEmbedUnimplementedContractorServiceServer()
}

func RegisterContractorServiceServer(s grpc.ServiceRegistrar, srv ContractorServiceServer) {
	// If the following call pancis, it indicates UnimplementedContractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractorService_ServiceDesc, srv)
}

func _ContractorService_SubmitBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).SubmitBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractorService_SubmitBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).SubmitBid(ctx, req.(*SubmitBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractorService_GetBidsForTender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).GetBidsForTender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractorService_GetBidsForTender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).GetBidsForTender(ctx, req.(*GetBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractorService_GetMyBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractorServiceServer).GetMyBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractorService_GetMyBids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractorServiceServer).GetMyBids(ctx, req.(*GetMyBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractorService_ServiceDesc is the grpc.ServiceDesc for ContractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tender.ContractorService",
	HandlerType: (*ContractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBid",
			Handler:    _ContractorService_SubmitBid_Handler,
		},
		{
			MethodName: "GetBidsForTender",
			Handler:    _ContractorService_GetBidsForTender_Handler,
		},
		{
			MethodName: "GetMyBids",
			Handler:    _ContractorService_GetMyBids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/contractors.proto",
}
