// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: tender.proto

package tender_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTenderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deadline    string  `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Budget      float64 `protobuf:"fixed64,4,opt,name=budget,proto3" json:"budget,omitempty"`
	ClientId    string  `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Attachment  string  `protobuf:"bytes,6,opt,name=attachment,proto3" json:"attachment,omitempty"` // Optional file URL
}

func (x *CreateTenderReq) Reset() {
	*x = CreateTenderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTenderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenderReq) ProtoMessage() {}

func (x *CreateTenderReq) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenderReq.ProtoReflect.Descriptor instead.
func (*CreateTenderReq) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenderReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTenderReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTenderReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateTenderReq) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *CreateTenderReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateTenderReq) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

type GetTendersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *GetTendersReq) Reset() {
	*x = GetTendersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTendersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTendersReq) ProtoMessage() {}

func (x *GetTendersReq) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTendersReq.ProtoReflect.Descriptor instead.
func (*GetTendersReq) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{1}
}

func (x *GetTendersReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type UpdateTenderStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenderId    string `protobuf:"bytes,1,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
	Status      string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g., "open", "closed", "awarded"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Budget      string `protobuf:"bytes,4,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *UpdateTenderStatusReq) Reset() {
	*x = UpdateTenderStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTenderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenderStatusReq) ProtoMessage() {}

func (x *UpdateTenderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenderStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateTenderStatusReq) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTenderStatusReq) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

func (x *UpdateTenderStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTenderStatusReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTenderStatusReq) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

type DeleteTenderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenderId string `protobuf:"bytes,1,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
}

func (x *DeleteTenderReq) Reset() {
	*x = DeleteTenderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTenderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenderReq) ProtoMessage() {}

func (x *DeleteTenderReq) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenderReq.ProtoReflect.Descriptor instead.
func (*DeleteTenderReq) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTenderReq) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

type TenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TenderResponse) Reset() {
	*x = TenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenderResponse) ProtoMessage() {}

func (x *TenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenderResponse.ProtoReflect.Descriptor instead.
func (*TenderResponse) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{4}
}

func (x *TenderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TendersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenders []*Tender `protobuf:"bytes,1,rep,name=tenders,proto3" json:"tenders,omitempty"`
}

func (x *TendersListResponse) Reset() {
	*x = TendersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TendersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TendersListResponse) ProtoMessage() {}

func (x *TendersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TendersListResponse.ProtoReflect.Descriptor instead.
func (*TendersListResponse) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{5}
}

func (x *TendersListResponse) GetTenders() []*Tender {
	if x != nil {
		return x.Tenders
	}
	return nil
}

type Tender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId    string  `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Title       string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline    string  `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Budget      float64 `protobuf:"fixed64,6,opt,name=budget,proto3" json:"budget,omitempty"`
	Status      string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Attachment  string  `protobuf:"bytes,8,opt,name=attachment,proto3" json:"attachment,omitempty"`
}

func (x *Tender) Reset() {
	*x = Tender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tender_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tender) ProtoMessage() {}

func (x *Tender) ProtoReflect() protoreflect.Message {
	mi := &file_tender_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tender.ProtoReflect.Descriptor instead.
func (*Tender) Descriptor() ([]byte, []int) {
	return file_tender_proto_rawDescGZIP(), []int{6}
}

func (x *Tender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tender) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Tender) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Tender) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tender) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *Tender) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *Tender) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tender) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

var File_tender_proto protoreflect.FileDescriptor

var file_tender_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xba, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x86, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x54, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x07,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0xd9, 0x01, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0xa0, 0x02, 0x0a, 0x0d, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tender_proto_rawDescOnce sync.Once
	file_tender_proto_rawDescData = file_tender_proto_rawDesc
)

func file_tender_proto_rawDescGZIP() []byte {
	file_tender_proto_rawDescOnce.Do(func() {
		file_tender_proto_rawDescData = protoimpl.X.CompressGZIP(file_tender_proto_rawDescData)
	})
	return file_tender_proto_rawDescData
}

var file_tender_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tender_proto_goTypes = []interface{}{
	(*CreateTenderReq)(nil),       // 0: tender.CreateTenderReq
	(*GetTendersReq)(nil),         // 1: tender.GetTendersReq
	(*UpdateTenderStatusReq)(nil), // 2: tender.UpdateTenderStatusReq
	(*DeleteTenderReq)(nil),       // 3: tender.DeleteTenderReq
	(*TenderResponse)(nil),        // 4: tender.TenderResponse
	(*TendersListResponse)(nil),   // 5: tender.TendersListResponse
	(*Tender)(nil),                // 6: tender.Tender
}
var file_tender_proto_depIdxs = []int32{
	6, // 0: tender.TendersListResponse.tenders:type_name -> tender.Tender
	0, // 1: tender.TenderService.CreateTender:input_type -> tender.CreateTenderReq
	1, // 2: tender.TenderService.GetTenders:input_type -> tender.GetTendersReq
	2, // 3: tender.TenderService.UpdateTenderStatus:input_type -> tender.UpdateTenderStatusReq
	3, // 4: tender.TenderService.DeleteTender:input_type -> tender.DeleteTenderReq
	4, // 5: tender.TenderService.CreateTender:output_type -> tender.TenderResponse
	5, // 6: tender.TenderService.GetTenders:output_type -> tender.TendersListResponse
	4, // 7: tender.TenderService.UpdateTenderStatus:output_type -> tender.TenderResponse
	4, // 8: tender.TenderService.DeleteTender:output_type -> tender.TenderResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tender_proto_init() }
func file_tender_proto_init() {
	if File_tender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTenderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTendersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTenderStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTenderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TendersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tender_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tender_proto_goTypes,
		DependencyIndexes: file_tender_proto_depIdxs,
		MessageInfos:      file_tender_proto_msgTypes,
	}.Build()
	File_tender_proto = out.File
	file_tender_proto_rawDesc = nil
	file_tender_proto_goTypes = nil
	file_tender_proto_depIdxs = nil
}
